To Do List:
 - Merge filing dictionaries to expand data range
 - Expand financial statement DFs to house the extra years

In [407]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import time
from datetime import datetime
import os

header = {'User-Agent': 'mdemiceli@gmail.com'}

# PULLING CIK NUMBERS AND TICKERS

In [408]:
megacap_tickers = pd.read_csv('nasdaq_megacap_tickers.csv') # tickers file downloaded from nasdaq.com

megacap_tickers = [x for x in megacap_tickers['Symbol']]
megacap_tickers

['AAPL',
 'ABBV',
 'AMZN',
 'AVGO',
 'BAC',
 'COST',
 'CSCO',
 'CVX',
 'DIS',
 'FB',
 'GOOG',
 'GOOGL',
 'HD',
 'JNJ',
 'JPM',
 'KO',
 'LLY',
 'MA',
 'MRK',
 'MSFT',
 'NVDA',
 'PEP',
 'PFE',
 'PG',
 'TMO',
 'TSLA',
 'UNH',
 'V',
 'VFC',
 'WMT',
 'XOM']

In [409]:
cik_tickers_json_url = r'https://www.sec.gov/files/company_tickers.json'

cik_tickers_bulk = requests.get(cik_tickers_json_url, headers=header)
decoded_cik_tickers_bulk = cik_tickers_bulk.json()

len(decoded_cik_tickers_bulk) # this is a mass json file with every sec registered company's cik, ticker, and name

12175

In [444]:
mega_caps = dict()
mega_caps['cik'] = []
mega_caps['ticker'] = []
mega_caps['name'] = []

for bulk in decoded_cik_tickers_bulk:
    
    # formatting cik nums
    diff = 10 - len(str(decoded_cik_tickers_bulk[str(bulk)]['cik_str']))
    cik_full = '0' * diff + str(decoded_cik_tickers_bulk[str(bulk)]['cik_str'])
    
    ticker_str = decoded_cik_tickers_bulk[str(bulk)]['ticker']
    
    if ticker_str in megacap_tickers:
        mega_caps['cik'].append(cik_full)
        mega_caps['ticker'].append(decoded_cik_tickers_bulk[str(bulk)]['ticker'])
        mega_caps['name'].append(decoded_cik_tickers_bulk[str(bulk)]['title'])
        

mega_caps

{'cik': ['0000320193',
  '0000789019',
  '0001652044',
  '0001018724',
  '0001318605',
  '0001326801',
  '0000731766',
  '0000200406',
  '0001045810',
  '0000104169',
  '0000080424',
  '0000034088',
  '0000019617',
  '0001141391',
  '0000354950',
  '0000093410',
  '0000070858',
  '0000059478',
  '0000021344',
  '0000078003',
  '0001551152',
  '0000077476',
  '0000909832',
  '0001730168',
  '0000310158',
  '0000097745',
  '0000858877',
  '0001744489',
  '0000103379',
  '0001403161',
  '0001652044'],
 'ticker': ['AAPL',
  'MSFT',
  'GOOGL',
  'AMZN',
  'TSLA',
  'FB',
  'UNH',
  'JNJ',
  'NVDA',
  'WMT',
  'PG',
  'XOM',
  'JPM',
  'MA',
  'HD',
  'CVX',
  'BAC',
  'LLY',
  'KO',
  'PFE',
  'ABBV',
  'PEP',
  'COST',
  'AVGO',
  'MRK',
  'TMO',
  'CSCO',
  'DIS',
  'VFC',
  'V',
  'GOOG'],
 'name': ['Apple Inc.',
  'MICROSOFT CORP',
  'Alphabet Inc.',
  'AMAZON COM INC',
  'Tesla, Inc.',
  'Meta Platforms, Inc.',
  'UNITEDHEALTH GROUP INC',
  'JOHNSON & JOHNSON',
  'NVIDIA CORP',
  'Walmart Inc.',
  'PROCTER & GAMBLE Co',
  'EXXON MOBIL CORP',
  'JPMORGAN CHASE & CO',
  'Mastercard Inc',
  'HOME DEPOT, INC.',
  'CHEVRON CORP',
  'BANK OF AMERICA CORP /DE/',
  'ELI LILLY & Co',
  'COCA COLA CO',
  'PFIZER INC',
  'AbbVie Inc.',
  'PEPSICO INC',
  'COSTCO WHOLESALE CORP /NEW',
  'Broadcom Inc.',
  'Merck & Co., Inc.',
  'THERMO FISHER SCIENTIFIC INC.',
  'CISCO SYSTEMS, INC.',
  'Walt Disney Co',
  'V F CORP',
  'VISA INC.',
  'Alphabet Inc.']}

In [411]:
# lens are 31 because Google is duplicated

print(len(mega_caps['cik']))
print(len(mega_caps['ticker']))
print(len(mega_caps['name']))

31
31
31

In [412]:
# Using company's cik number to pull its submissions url file and geenrate a master list

master_submission_urls = []

for cik in mega_caps['cik']:
    
    base_submissions_url = r'https://data.sec.gov/submissions/CIK' + cik + r'.json'
    master_submission_urls.append(base_submissions_url)

    
print(master_submission_urls)
print(len(master_submission_urls))

['https://data.sec.gov/submissions/CIK0000320193.json', 'https://data.sec.gov/submissions/CIK0000789019.json', 'https://data.sec.gov/submissions/CIK0001652044.json', 'https://data.sec.gov/submissions/CIK0001018724.json', 'https://data.sec.gov/submissions/CIK0001318605.json', 'https://data.sec.gov/submissions/CIK0001326801.json', 'https://data.sec.gov/submissions/CIK0000731766.json', 'https://data.sec.gov/submissions/CIK0000200406.json', 'https://data.sec.gov/submissions/CIK0001045810.json', 'https://data.sec.gov/submissions/CIK0000104169.json', 'https://data.sec.gov/submissions/CIK0000080424.json', 'https://data.sec.gov/submissions/CIK0000034088.json', 'https://data.sec.gov/submissions/CIK0000019617.json', 'https://data.sec.gov/submissions/CIK0001141391.json', 'https://data.sec.gov/submissions/CIK0000354950.json', 'https://data.sec.gov/submissions/CIK0000093410.json', 'https://data.sec.gov/submissions/CIK0000070858.json', 'https://data.sec.gov/submissions/CIK0000059478.json', 'https://data.sec.gov/submissions/CIK0000021344.json', 'https://data.sec.gov/submissions/CIK0000078003.json', 'https://data.sec.gov/submissions/CIK0001551152.json', 'https://data.sec.gov/submissions/CIK0000077476.json', 'https://data.sec.gov/submissions/CIK0000909832.json', 'https://data.sec.gov/submissions/CIK0001730168.json', 'https://data.sec.gov/submissions/CIK0000310158.json', 'https://data.sec.gov/submissions/CIK0000097745.json', 'https://data.sec.gov/submissions/CIK0000858877.json', 'https://data.sec.gov/submissions/CIK0001744489.json', 'https://data.sec.gov/submissions/CIK0000103379.json', 'https://data.sec.gov/submissions/CIK0001403161.json', 'https://data.sec.gov/submissions/CIK0001652044.json']
31

In [413]:
master_filings_bulk = []

for url in master_submission_urls: # change range to full master_submission_urls list once confident

    # pulling json object
    content = requests.get(url, headers=header)
    decoded_content = content.json()
    
    # pulling relevant features (**additional company level details can be pulled from here)
    js2 = dict()
    js2['cik'] = decoded_content['cik']
    js2['tickers'] = decoded_content['tickers']
    js2['accessionNumbers'] = decoded_content['filings']['recent']['accessionNumber']
    js2['filingDate'] = decoded_content['filings']['recent']['filingDate']
    js2['forms'] = decoded_content['filings']['recent']['form']
    
    master_filings_bulk.append(js2)

In [445]:
accession_df = pd.DataFrame(data=master_filings_bulk)
accession_df

,cik,tickers,accessionNumbers,filingDate,forms
0,320193,[AAPL],"[0001193125-22-128368, 0001193125-22-128361, 0...","[2022-04-29, 2022-04-29, 2022-04-29, 2022-04-2...","[S-8, S-8 POS, S-8 POS, 10-Q, 8-K, 4, 4, 4, 4,..."
1,789019,[MSFT],"[0001564590-22-015675, 0001193125-22-120207, 0...","[2022-04-26, 2022-04-26, 2022-04-19, 2022-04-1...","[10-Q, 8-K, 4, 4, 4, 4, 11-K, 4, 4, 4, 4, 4, 4..."
2,0001652044,"[GOOGL, GOOG]","[0001209191-22-027197, 0001209191-22-027181, 0...","[2022-05-04, 2022-05-04, 2022-04-29, 2022-04-2...","[4, 4, PX14A6G, PX14A6G, PX14A6G, PX14A6G, 4, ..."
3,1018724,[AMZN],"[0001018724-22-000013, 0001018724-22-000011, 0...","[2022-04-29, 2022-04-28, 2022-04-25, 2022-04-2...","[10-Q, 8-K, PX14A6G, PX14A6G, PX14A6G, DEFA14A..."
4,0001318605,[TSLA],"[0001790565-22-000006, 0000899243-22-016671, 0...","[2022-05-04, 2022-05-04, 2022-05-04, 2022-05-0...","[4, 4, 4, 8-K, 10-K/A, 4, 4, 4, 4, 4, 4, 4, 4,..."
5,1326801,[FB],"[0000950103-22-007355, 0001214659-22-005924, 0...","[2022-04-28, 2022-04-28, 2022-04-28, 2022-04-2...","[4, PX14A6G, 10-Q, 8-K, PX14A6G, PX14A6G, 4, P..."
6,0000731766,[UNH],"[0000731766-22-000019, 0001209191-22-025383, 0...","[2022-05-04, 2022-04-22, 2022-04-22, 2022-04-2...","[10-Q, 3, DEFA14A, DEF 14A, 8-K, 4, 4, 4, 4, 4..."
7,200406,[JNJ],"[0001193125-22-134336, 0000200406-22-000048, 0...","[2022-04-29, 2022-04-29, 2022-04-29, 2022-04-2...","[S-8, 10-Q, 8-K, 4, 8-K, PX14A6G, PX14A6G, PX1..."
8,1045810,[NVDA],"[0001045810-22-000070, 0001045810-22-000068, 0...","[2022-04-20, 2022-04-19, 2022-04-19, 2022-04-0...","[DEFA14A, DEF 14A, DEF 14A, PRE 14A, 4, 4, 4, ..."
9,104169,[WMT],"[0001127602-22-012768, 0001214659-22-005695, 0...","[2022-04-29, 2022-04-25, 2022-04-21, 2022-04-2...","[4, PX14A6G, DEFA14A, DEF 14A, 4, 8-K, 25-NSE,..."
10,80424,[PG],"[0001127602-22-012755, 0001127602-22-012555, 0...","[2022-04-29, 2022-04-27, 2022-04-26, 2022-04-2...","[4, 4, 4, 4, 4, 4, 10-Q, 8-K, 8-K, 8-K, 8-K, 3..."
11,0000034088,[XOM],"[0000950103-22-007913, 0000034088-22-000026, 0...","[2022-05-04, 2022-05-04, 2022-05-03, 2022-04-2...","[S-8, 10-Q, 4, 3, SC 13D, PX14A6G, 8-K, PX14A6..."
12,0000019617,"[JPM, JPM-PC, JPM-PD, JPM-PM, JPM-PL, JPM-PK, ...","[0001213900-22-024010, 0001213900-22-024009, 0...","[2022-05-04, 2022-05-04, 2022-05-04, 2022-05-0...","[424B8, 424B2, 424B2, 424B2, 424B2, 424B2, 424..."
13,1141391,[MA],"[0001141391-22-000105, 0001141391-22-000104, 0...","[2022-05-03, 2022-05-03, 2022-04-29, 2022-04-2...","[4, 4, DEFA14A, DEF 14A, IRANNOTICE, 10-Q, 8-K..."
14,0000354950,[HD],"[0001926550-22-000003, 0001214659-22-005849, 0...","[2022-05-04, 2022-04-27, 2022-04-19, 2022-04-1...","[3, PX14A6G, 8-K, PX14A6G, DEF 14A, 4, 4, 8-K,..."
15,0000093410,[CVX],"[0000093410-22-000028, 0000093410-22-000026, 0...","[2022-05-04, 2022-05-04, 2022-05-04, 2022-05-0...","[10-Q/A, 10-Q, DEFA14A, PX14A6G, PX14A6G, 8-K,..."
16,0000070858,"[BAC, BML-PG, BML-PH, BML-PL, BAC-PE, BAC-PB, ...","[0001481057-22-001728, 0001481057-22-001727, 0...","[2022-05-04, 2022-05-04, 2022-05-04, 2022-05-0...","[424B2, 424B2, 424B2, 424B2, 424B2, 424B2, 424..."
17,0000059478,[LLY],"[0000059478-22-000138, 0000059478-22-000133, 0...","[2022-05-04, 2022-04-29, 2022-04-28, 2022-04-1...","[8-K, 10-Q, 8-K, 4, 4, 4, 4, 4, 8-K, PX14A6G, ..."
18,21344,[KO],"[0000021344-22-000016, 0001552781-22-000366, 0...","[2022-04-28, 2022-04-27, 2022-04-27, 2022-04-2...","[10-Q, 8-K, 4, 4, 8-K, PX14A6G, 4, 4/A, 4, 4, ..."
19,78003,[PFE],"[0000078003-22-000068, 0000078003-22-000066, 0...","[2022-05-03, 2022-05-02, 2022-05-02, 2022-05-0...","[8-K, 8-K, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,..."
20,1551152,[ABBV],"[0001551152-22-000012, 0001551152-22-000010, 0...","[2022-04-29, 2022-04-29, 2022-04-21, 2022-04-1...","[8-K, 8-K, 8-K, 8-K, PX14A6G, 4, 4, 4, PX14A6G..."
21,77476,[PEP],"[0000077476-22-000021, 0000077476-22-000020, 0...","[2022-04-26, 2022-04-26, 2022-04-15, 2022-04-0...","[8-K, 10-Q, 8-K, 4, PX14A6G, DEFA14A, DEF 14A,..."
22,909832,[COST],"[0001193125-22-104414, 0001209191-22-023886, 0...","[2022-04-13, 2022-04-08, 2022-04-08, 2022-04-0...","[8-K, 4, 4, 3/A, 4, 4, 3, 10-Q, 8-K, 3, 8-K, S..."
23,1730168,"[AVGO, AVGOP]","[0001193125-22-108067, 0001193125-22-105918, 0...","[2022-04-18, 2022-04-15, 2022-04-06, 2022-04-0...","[8-K, 8-K, 4, 4, 4, 4, 4, 4, 4, 8-K, 4, 8-K, 8..."
24,0000310158,[MRK],"[0001127602-22-013291, 0001127602-22-013286, 0...","[2022-05-04, 2022-05-04, 2022-05-04, 2022-05-0...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ..."
25,0000097745,[TMO],"[0001127602-22-013268, 0001127602-22-013250, 0...","[2022-05-04, 2022-05-04, 2022-04-28, 2022-04-0...","[4, 4, 8-K, DEFA14A, DEF 14A, 4, 4, 4, 4, 3, 4..."
26,858877,[CSCO],"[0001193125-22-086807, 0001209191-22-019739, 0...","[2022-03-28, 2022-03-17, 2022-03-17, 2022-03-1...","[8-K, 4, 4, 4, 4, 4/A, 4, 4, 4, 4, IRANNOTICE,..."
27,0001744489,[DIS],"[0001744489-22-000093, 0001744489-22-000092, 0...","[2022-04-04, 2022-04-04, 2022-04-04, 2022-04-0...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, S-3ASR, 4, 4, 4..."
28,103379,[VFC],"[0001104659-22-044260, 0001127602-22-011677, 0...","[2022-04-08, 2022-04-06, 2022-04-06, 2022-04-0...","[SC 13G/A, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,..."
29,1403161,[V],"[0001127602-22-012928, 0001403161-22-000027, 0...","[2022-05-02, 2022-04-28, 2022-04-26, 2022-04-1...","[4, 10-Q, 8-K, 4, 3, 8-K, 4, 4, 4, 4, 8-K, 4, ..."
30,0001652044,"[GOOGL, GOOG]","[0001209191-22-027197, 0001209191-22-027181, 0...","[2022-05-04, 2022-05-04, 2022-04-29, 2022-04-2...","[4, 4, PX14A6G, PX14A6G, PX14A6G, PX14A6G, 4, ..."

In [507]:
accession_ten_k = dict()
accession_ten_k['ticker'] = []
accession_ten_k['accessionNumbers'] = []

for row in range(len(accession_df)):
    
    # pulling all the data for each row in df
    company = accession_df.iloc[row]
    
    # pulling out accession nums and form types
    accessionNumbers = company[2]
    forms = company[4]
    
    company_df = pd.DataFrame(data=[accessionNumbers, forms]).T
    company_df.columns = ['accessionNumbers', 'forms']
    
    # taking only the first ticker since this is usually the main
    accession_ten_k['ticker'].append(company[1][0])
    
    # this appends all accession nums when form type == 10-K
    accession_ten_k['accessionNumbers'].append(company_df['accessionNumbers'][company_df['forms'] == '10-K'])

    
accession_ten_k # dict organized by ticker and accessions for 10-K filings only

{'ticker': ['AAPL',
  'MSFT',
  'GOOGL',
  'AMZN',
  'TSLA',
  'FB',
  'UNH',
  'JNJ',
  'NVDA',
  'WMT',
  'PG',
  'XOM',
  'JPM',
  'MA',
  'HD',
  'CVX',
  'BAC',
  'LLY',
  'KO',
  'PFE',
  'ABBV',
  'PEP',
  'COST',
  'AVGO',
  'MRK',
  'TMO',
  'CSCO',
  'DIS',
  'VFC',
  'V',
  'GOOGL'],
 'accessionNumbers': [48     0000320193-21-000105
  117    0000320193-20-000096
  188    0000320193-19-000119
  258    0000320193-18-000145
  346    0000320193-17-000070
  491    0001628280-16-020309
  608    0001193125-15-356351
  737    0001193125-14-383437
  846    0001193125-13-416534
  945    0001193125-12-444068
  Name: accessionNumbers, dtype: object,
  114    0001564590-21-039151
  268    0001564590-20-034944
  432    0001564590-19-027952
  598    0001564590-18-019062
  758    0001564590-17-014900
  921    0001193125-16-662209
  Name: accessionNumbers, dtype: object,
  130    0001652044-22-000019
  425    0001652044-21-000010
  541    0001652044-20-000008
  689    0001652044-19-000004
  856    0001652044-18-000007
  Name: accessionNumbers, dtype: object,
  43     0001018724-22-000005
  200    0001018724-21-000004
  332    0001018724-20-000004
  446    0001018724-19-000004
  566    0001018724-18-000005
  681    0001018724-17-000011
  778    0001018724-16-000172
  863    0001018724-15-000006
  954    0001018724-14-000006
  Name: accessionNumbers, dtype: object,
  35     0000950170-22-000796
  167    0001564590-21-004599
  305    0001564590-20-004475
  458    0001564590-19-003165
  565    0001564590-18-002956
  671    0001564590-17-003118
  796    0001564590-16-013195
  872    0001564590-15-001031
  930    0001193125-14-069681
  Name: accessionNumbers, dtype: object,
  53     0001326801-22-000018
  423    0001326801-21-000014
  647    0001326801-20-000013
  862    0001326801-19-000009
  Name: accessionNumbers, dtype: object,
  61     0000731766-22-000008
  213    0000731766-21-000013
  398    0000731766-20-000006
  594    0000731766-19-000005
  794    0000731766-18-000005
  Name: accessionNumbers, dtype: object,
  36     0000200406-22-000022
  123    0000200406-21-000008
  256    0000200406-20-000010
  338    0000200406-19-000009
  423    0000200406-18-000005
  510    0000200406-17-000006
  616    0000200406-16-000071
  715    0000200406-15-000004
  830    0000200406-14-000033
  928    0000200406-13-000038
  Name: accessionNumbers, dtype: object,
  12     0001045810-22-000036
  128    0001045810-21-000010
  249    0001045810-20-000010
  340    0001045810-19-000023
  427    0001045810-18-000010
  518    0001045810-17-000027
  621    0001045810-16-000205
  707    0001045810-15-000036
  809    0001045810-14-000030
  876    0001045810-13-000008
  923    0001045810-12-000013
  Name: accessionNumbers, dtype: object,
  22     0000104169-22-000012
  261    0000104169-21-000033
  435    0000104169-20-000011
  609    0000104169-19-000016
  851    0000104169-18-000028
  Name: accessionNumbers, dtype: object,
  185    0000080424-21-000100
  415    0000080424-20-000053
  597    0000080424-19-000050
  849    0000080424-18-000055
  Name: accessionNumbers, dtype: object,
  23     0000034088-22-000011
  364    0000034088-21-000012
  521    0000034088-20-000016
  614    0000034088-19-000010
  714    0000034088-18-000015
  835    0000034088-17-000017
  967    0000034088-16-000065
  Name: accessionNumbers, dtype: object,
  3429    0000019617-22-000272
  Name: accessionNumbers, dtype: object,
  47     0001141391-22-000023
  163    0001141391-21-000018
  283    0001141391-20-000032
  398    0001141391-19-000013
  472    0001141391-18-000009
  541    0001141391-17-000014
  644    0001141391-16-000085
  749    0001141391-15-000011
  847    0001141391-14-000003
  935    0001141391-13-000003
  Name: accessionNumbers, dtype: object,
  28     0000354950-22-000070
  129    0000354950-21-000089
  250    0000354950-20-000015
  353    0000354950-19-000010
  454    0000354950-18-000019
  550    0000354950-17-000005
  647    0000354950-16-000060
  752    0000354950-15-000008
  849    0000354950-14-000008
  955    0000354950-13-000008
  Name: accessionNumbers, dtype: object,
  26     0000093410-22-000019
  152    0000093410-21-000009
  290    0000093410-20-000010
  398    0000093410-19-000008
  486    0000093410-18-000010
  570    0000093410-17-000013
  667    0000093410-16-000049
  764    0000093410-15-000010
  849    0000093410-14-000011
  956    0000093410-13-000003
  Name: accessionNumbers, dtype: object,
  572    0000070858-22-000062
  Name: accessionNumbers, dtype: object,
  52     0000059478-22-000068
  207    0000059478-21-000083
  359    0000059478-20-000057
  577    0000059478-19-000082
  811    0000059478-18-000089
  952    0000059478-17-000098
  Name: accessionNumbers, dtype: object,
  40     0000021344-22-000009
  155    0000021344-21-000008
  299    0000021344-20-000006
  419    0000021344-19-000014
  517    0000021344-18-000008
  625    0000021344-17-000009
  748    0000021344-16-000050
  904    0000021344-15-000005
  Name: accessionNumbers, dtype: object,
  75     0000078003-22-000027
  284    0000078003-21-000038
  543    0000078003-20-000014
  785    0000078003-19-000015
  Name: accessionNumbers, dtype: object,
  45     0001551152-22-000007
  144    0001551152-21-000008
  273    0001551152-20-000007
  374    0001551152-19-000008
  495    0001551152-18-000014
  595    0001551152-17-000004
  695    0001047469-16-010239
  812    0001047469-15-000995
  926    0001047469-14-001154
  988    0001047469-13-002827
  Name: accessionNumbers, dtype: object,
  20     0000077476-22-000010
  96     0000077476-21-000007
  188    0000077476-20-000015
  272    0000077476-19-000017
  346    0000077476-18-000012
  432    0000077476-17-000010
  526    0000077476-16-000066
  636    0000077476-15-000012
  744    0000077476-14-000007
  849    0001445305-13-000278
  953    0001193125-12-081822
  Name: accessionNumbers, dtype: object,
  50     0000909832-21-000014
  127    0000909832-20-000017
  219    0000909832-19-000019
  290    0000909832-18-000013
  435    0000909832-17-000014
  570    0000909832-16-000032
  673    0000909832-15-000014
  800    0000909832-14-000021
  939    0001445305-13-002422
  Name: accessionNumbers, dtype: object,
  49     0001730168-21-000153
  137    0001730168-20-000226
  262    0001730168-19-000144
  354    0001730168-18-000084
  Name: accessionNumbers, dtype: object,
  40     0000310158-22-000003
  154    0000310158-21-000004
  251    0000310158-20-000005
  371    0000310158-19-000014
  495    0000310158-18-000005
  595    0000310158-17-000010
  702    0000310158-16-000063
  803    0000310158-15-000005
  964    0000310158-14-000009
  Name: accessionNumbers, dtype: object,
  26     0000097745-22-000011
  141    0000097745-21-000011
  293    0000097745-20-000009
  400    0000097745-19-000007
  492    0000097745-18-000006
  650    0000097745-17-000007
  800    0000097745-16-000043
  943    0000097745-15-000007
  Name: accessionNumbers, dtype: object,
  67     0000858877-21-000013
  231    0000858877-20-000010
  382    0000858877-19-000012
  493    0000858877-18-000011
  601    0000858877-17-000016
  749    0000858877-16-000117
  881    0000858877-15-000070
  Name: accessionNumbers, dtype: object,
  68     0001744489-21-000220
  188    0001744489-20-000197
  314    0001744489-19-000225
  Name: accessionNumbers, dtype: object,
  65     0000103379-21-000006
  155    0000103379-20-000006
  319    0000103379-19-000006
  420    0000103379-18-000003
  513    0001628280-17-002027
  622    0001193125-16-489832
  725    0001193125-15-075174
  849    0001193125-14-069474
  955    0001193125-13-079974
  Name: accessionNumbers, dtype: object,
  58     0001403161-21-000060
  150    0001403161-20-000070
  234    0001403161-19-000050
  295    0001403161-18-000055
  356    0001403161-17-000044
  423    0001403161-16-000058
  503    0001403161-15-000013
  576    0001403161-14-000017
  636    0001403161-13-000011
  744    0001384108-12-000011
  848    0001193125-11-315956
  909    0001193125-10-265236
  977    0001193125-09-239249
  Name: accessionNumbers, dtype: object,
  130    0001652044-22-000019
  425    0001652044-21-000010
  541    0001652044-20-000008
  689    0001652044-19-000004
  856    0001652044-18-000007
  Name: accessionNumbers, dtype: object]}

In [508]:
df_ten_k = pd.DataFrame(accession_ten_k)
df_ten_k

   ticker                                   accessionNumbers
0    AAPL  48     0000320193-21-000105
117    0000320193-...
1    MSFT  114    0001564590-21-039151
268    0001564590-...
2   GOOGL  130    0001652044-22-000019
425    0001652044-...
3    AMZN  43     0001018724-22-000005
200    0001018724-...
4    TSLA  35     0000950170-22-000796
167    0001564590-...
5      FB  53     0001326801-22-000018
423    0001326801-...
6     UNH  61     0000731766-22-000008
213    0000731766-...
7     JNJ  36     0000200406-22-000022
123    0000200406-...
8    NVDA  12     0001045810-22-000036
128    0001045810-...
9     WMT  22     0000104169-22-000012
261    0000104169-...
10     PG  185    0000080424-21-000100
415    0000080424-...
11    XOM  23     0000034088-22-000011
364    0000034088-...
12    JPM  3429    0000019617-22-000272
Name: accessionNu...
13     MA  47     0001141391-22-000023
163    0001141391-...
14     HD  28     0000354950-22-000070
129    0000354950-...
15    CVX  26     0000093410-22-000019
152    0000093410-...
16    BAC  572    0000070858-22-000062
Name: accessionNum...
17    LLY  52     0000059478-22-000068
207    0000059478-...
18     KO  40     0000021344-22-000009
155    0000021344-...
19    PFE  75     0000078003-22-000027
284    0000078003-...
20   ABBV  45     0001551152-22-000007
144    0001551152-...
21    PEP  20     0000077476-22-000010
96     0000077476-...
22   COST  50     0000909832-21-000014
127    0000909832-...
23   AVGO  49     0001730168-21-000153
137    0001730168-...
24    MRK  40     0000310158-22-000003
154    0000310158-...
25    TMO  26     0000097745-22-000011
141    0000097745-...
26   CSCO  67     0000858877-21-000013
231    0000858877-...
27    DIS  68     0001744489-21-000220
188    0001744489-...
28    VFC  65     0000103379-21-000006
155    0000103379-...
29      V  58     0001403161-21-000060
150    0001403161-...
30  GOOGL  130    0001652044-22-000019
425    0001652044-...

# THIS IS AS FAR AS I HAVE GOTTEN IN THE NEWEST ROUND OF EDITS

-MD

In [447]:
'''
TESTING
'''

accession_ten_k = dict()
accession_ten_k['cik'] = []
accession_ten_k['accessionNumbers'] = []
accession_ten_k['filingDate'] = []

for row in range(2):

    singular_company = dict()
    singular_company['cik'] = accession_df['cik'][row]
    singular_company['accessionNumbers'] = accession_df['accessionNumbers'][row]
    singular_company['filingDates'] = accession_df['filingDate'][row]
    singular_company['forms'] = accession_df['forms'][row]
    
    
    singular_df = pd.DataFrame(data=singular_company)
 

    accession_nums = singular_df['accessionNumbers'][singular_df['forms'] == '10-K']
    accession_ten_k['accessionNumbers'].append(new_accession_nums)
    
    ten_k_filing_dates = singular_df['filingDates'][singular_df['forms'] == '10-K']


# # removing '-' from accession nums
# for num in accession_nums:
#         new_num = num.replace('-', '')
#         accession_ten_k['accessionNumbers'].append(new_num)
    
# # duplicating cik num for each company filing row
# cik_list = []
# for i in range(len(accession_ten_k['accessionNumbers'])):
#     accession_ten_k['cik'].append(accession_df['cik'][row])

# # changing to datetime
# for date in ten_k_filing_dates:
#     datetime = pd.to_datetime(date, format='%Y/%m/%d')
#     accession_ten_k['filingDate'].append(datetime)
        
        
# accession_ten_k
# accession_nums

In [194]:
print(len(accession_ten_k['cik']))
print(len(accession_ten_k['accessionNumbers']))
print(len(accession_ten_k['filingDate']))

7
7
7

In [116]:
singular_df['accessionNumbers'][singular_df['forms'] == '10-K']

48     0000320193-21-000105
117    0000320193-20-000096
188    0000320193-19-000119
258    0000320193-18-000145
346    0000320193-17-000070
491    0001628280-16-020309
608    0001193125-15-356351
737    0001193125-14-383437
846    0001193125-13-416534
945    0001193125-12-444068
Name: accessionNumbers, dtype: object

In [39]:
# forms = submissions_mass['filings']['recent']['form']

# filing_dates = submissions_mass['filings']['recent']['filingDate']
# filing_dates_datetime = []
# for date in filing_dates:
#     date_time = pd.to_datetime(date, infer_datetime_format=True)
#     filing_dates_datetime.append(date_time)

    
# accession_numbers = submissions_mass['filings']['recent']['accessionNumber']
# accession_numbers_clean = []
# for number in accession_numbers:
#     accession_numbers_clean.append(number.replace('-', ''))
    
    
# submission_data = {'FilingDates': filing_dates_datetime, 'AccessionNumber':  accession_numbers_clean, 'Form': forms}

In [24]:
# dates = pd.DatetimeIndex(submissions_df['FilingDates']).year
# dates

## Cleaning Submissions Data & Establishing Dataframe

In [25]:
print(len(submission_data['FilingDates']))
print(len(submission_data['AccessionNumber']))
print(len(submission_data['Form']))

1009
1009
1009

In [38]:
submissions_df = pd.DataFrame(data=submission_data)

In [27]:
accession_ten_k = submissions_df['AccessionNumber'][submissions_df['Form'] == '10-K']
accession_ten_k

64     000106528022000036
316    000106528021000040
594    000106528020000040
842    000106528019000043
Name: AccessionNumber, dtype: object

# SCRAPING FINANCIAL STATEMENT DATA FROM FILING SUMMARY

In [28]:
base_url = r'https://www.sec.gov/Archives/edgar/data/'
cik = r'0001065280'
accession = r'000106528022000036'

filing_url = base_url + cik + '/' + accession + '/index.json'

filing_content = requests.get(filing_url, headers=header).json()

for file in filing_content['directory']['item']:
    
    # grab the filing summary and create a new url leading to the file so we can download it
    if file['name'] == 'FilingSummary.xml':
        
        xml_summary = r'https://www.sec.gov' + filing_content['directory']['name'] + '/' + file['name']
        
        print('-'*100)
        print('File Name: ' + file['name'])
        print('File Path: ' + xml_summary)

----------------------------------------------------------------------------------------------------
File Name: FilingSummary.xml
File Path: https://www.sec.gov/Archives/edgar/data/1065280/000106528022000036/FilingSummary.xml

In [448]:
base_url = xml_summary.replace('FilingSummary.xml', '')
content = requests.get(xml_summary, headers=header).content
soup = BeautifulSoup(content, 'lxml')

reports = soup.find('myreports')

master_reports = []

for report in reports.find_all('report')[:-1]:
    
    report_dict = dict()
    report_dict['name_short'] = report.shortname.text
    report_dict['name_long'] = report.longname.text
    report_dict['position'] = report.position.text
    report_dict['category'] = report.menucategory.text
    report_dict['url'] = base_url + report.htmlfilename.text
    
    master_reports.append(report_dict)

    
statements_url = []

for report_dict in master_reports:
    
    item1 = r'Consolidated Balance Sheets'.upper()
    item2 = r'Consolidated Statements of Operations'.upper()
    item3 = r'Consolidated Statements of Cash Flows'.upper()
    
    report_list = [item1, item2, item3]
    
    if report_dict['name_short'] in report_list:
        print('-'*100)
        print(report_dict['name_short'])
        print(report_dict['url'])
        
        statements_url.append(report_dict['url'])

NameError: name 'xml_summary' is not defined

In [42]:
statements_data = []

for statement in statements_url:
    
    statement_data = dict()
    statement_data['headers'] = []
    statement_data['sections'] = []
    statement_data['data'] = []
    
    content = requests.get(statement, headers=header).content
    report_soup = BeautifulSoup(content, 'html')
    
    for index, row in enumerate(report_soup.table.find_all('tr')):
        
        cols = row.find_all('td')
        
        if (len(row.find_all('th')) == 0 and len(row.find_all('strong')) == 0):
            
            reg_row = [ele.text.strip() for ele in cols]
            statement_data['data'].append(reg_row)
            
        elif (len(row.find_all('th')) == 0 and len(row.find_all('strong')) != 0):
            
            sec_row = cols[0].text.strip()
            statement_data['sections'].append(sec_row)
            
        elif (len(row.find_all('th')) != 0):
            
            hed_row = [ele.text.strip() for ele in row.find_all('th')]
            statement_data['headers'].append(hed_row)
              
        else:
              print('We encountered an error.')
              
    statements_data.append(statement_data)

In [36]:
income_headers = statements_data[0]['headers'][1]
income_data = statements_data[0]['data']

# put the data into a df
income_df = pd.DataFrame(income_data)

# define an rename index col
income_df.index = income_df[0]
income_df.index.name = 'Category'
income_df = income_df.drop(0, axis=1)

# get rid of the $, (), and convert empty cells to NaNs
income_df = income_df.replace('[\$,)]', '', regex=True)\
                     .replace('[(]', '-', regex=True)\
                     .replace('', 'NaN', regex=True)

# everything otiginally comes in as string, so we onvert to float
income_df = income_df.astype(float)

# change column headers
income_df.columns = income_headers

income_df

,"Dec. 31, 2021","Dec. 31, 2020","Dec. 31, 2019"
Category,,,
Revenues,29697844.00,24996056.00,20156447.00
Cost of revenues,17332683.00,15276319.00,12440213.00
Marketing,2545146.00,2228362.00,2652462.00
Technology and development,2273885.00,1829600.00,1545149.00
General and administrative,1351621.00,1076486.00,914369.00
Operating income,6194509.00,4585289.00,2604254.00
Interest expense,-765620.00,-767499.00,-626023.00
Interest and other income (expense),411214.00,-618441.00,84000.00
Income before income taxes,5840103.00,3199349.00,2062231.00
Provision for income taxes,-723875.00,-437954.00,-195315.00
Net income,5116228.00,2761395.00,1866916.00
Basic (in USD per share),11.55,6.26,4.26
Diluted (in USD per share),11.24,6.08,4.13
Basic (in shares),443155.00,440922.00,437799.00
Diluted (in shares),455372.00,454208.00,451765.00

In [32]:
socf_headers = statements_data[1]['headers'][1]
socf_data = statements_data[1]['data']

# put the data into a df
socf_df = pd.DataFrame(socf_data)

# define an rename index col
socf_df.index = socf_df[0]
socf_df.index.name = 'Category'
socf_df = socf_df.drop(0, axis=1)


# get rid of the $, (), and convert empty cells to NaNs
socf_df = socf_df.replace('[\$,)]', '', regex=True)\
                     .replace('[(]', '-', regex=True)\
                     .replace('', 'NaN', regex=True)

# everything otiginally comes in as string, so we onvert to float
socf_df = socf_df.astype(float)

# change column headers
socf_df.columns = socf_headers

socf_df

,"Dec. 31, 2021","Dec. 31, 2020","Dec. 31, 2019"
Category,,,
Net income,5116228.0,2761395.0,1866916.0
Additions to content assets,-17702202.0,-11779284.0,-13916683.0
Change in content liabilities,232898.0,-757433.0,-694011.0
Amortization of content assets,12230367.0,10806912.0,9216247.0
"Depreciation and amortization of property, equipment and intangibles",208412.0,115710.0,103579.0
Stock-based compensation expense,403220.0,415180.0,405376.0
Foreign currency remeasurement loss (gain) on debt,-430661.0,533278.0,-45576.0
Other non-cash items,376777.0,293126.0,228230.0
Deferred income taxes,199548.0,70066.0,-94443.0
Other current assets,-369681.0,-187623.0,-252113.0
Accounts payable,145115.0,-41605.0,96063.0
Accrued expenses and other liabilities,180338.0,198183.0,157778.0
Deferred revenue,91350.0,193247.0,163846.0
Other non-current assets and liabilities,-289099.0,-194075.0,-122531.0
Net cash provided by (used in) operating activities,392610.0,2427077.0,-2887322.0
Purchases of property and equipment,-524585.0,-497923.0,-253035.0
Change in other assets,-26919.0,-7431.0,-134029.0
Acquisitions,-788349.0,0.0,0.0
Net cash used in investing activities,-1339853.0,-505354.0,-387064.0
Proceeds from issuance of debt,0.0,1009464.0,4469306.0
Debt issuance costs,0.0,-7559.0,-36134.0
Repayments of debt,-500000.0,0.0,0.0
Proceeds from issuance of common stock,174414.0,235406.0,72490.0
Repurchases of common stock,-600022.0,0.0,0.0
Taxes paid related to net share settlement of equity awards,-224168.0,0.0,0.0
Net cash provided by (used in) financing activities,-1149776.0,1237311.0,4505662.0
"Effect of exchange rate changes on cash, cash equivalents and restricted cash",-86740.0,36050.0,469.0
"Net increase (decrease) in cash, cash equivalents and restricted cash",-2183759.0,3195084.0,1231745.0
"Cash, cash equivalents and restricted cash, beginning of year",8238870.0,5043786.0,3812041.0
"Cash, cash equivalents and restricted cash, end of year",6055111.0,8238870.0,5043786.0
Income taxes paid,509265.0,291582.0,400658.0
Interest paid,763432.0,762904.0,599132.0

In [33]:
bs_headers = statements_data[2]['headers'][0]
main, fy21, fy20 = bs_headers
bs_headers = fy21, fy20

bs_data = statements_data[2]['data']

# put the data into a df
bs_df = pd.DataFrame(bs_data)

# define an rename index col
bs_df.index = bs_df[0]
bs_df.index.name = 'Category'
bs_df = bs_df.drop(0, axis=1)


# get rid of the $, (), and convert empty cells to NaNs
bs_df = bs_df.replace('[\$,)]', '', regex=True)\
             .replace('[(]', '-', regex=True)\
             .replace('', 'NaN', regex=True)

# everything otiginally comes in as string, so we onvert to float
bs_df = bs_df.astype(float)

# change column headers
bs_df.columns = bs_headers

bs_df

,"Dec. 31, 2021","Dec. 31, 2020"
Category,,
Cash and cash equivalents,6027804.0,8205550.0
Other current assets,2042021.0,1556030.0
Total current assets,8069825.0,9761580.0
"Content assets, net",30919539.0,25383950.0
"Property and equipment, net",1323453.0,960183.0
Other non-current assets,4271846.0,3174646.0
Total assets,44584663.0,39280359.0
Current content liabilities,4292967.0,4429536.0
Accounts payable,837483.0,656183.0
Accrued expenses and other liabilities,1449351.0,1102196.0
Deferred revenue,1209342.0,1117992.0
Short-term debt,699823.0,499878.0
Total current liabilities,8488966.0,7805785.0
Non-current content liabilities,3094213.0,2618084.0
Long-term debt,14693072.0,15809095.0
Other non-current liabilities,2459164.0,1982155.0
Total liabilities,28735415.0,28215119.0
Commitments and contingencies,NaN,NaN
"Preferred stock, $0.001 par value; 10,000,000 shares authorized at December 31, 2021 and December 31, 2020; no shares issued and outstanding at December 31, 2021 and December 31, 2020",0.0,0.0
"Common stock, 0.001 par value; 4,990,000,000 shares authorized at December 31, 2021 and December 31, 2020; 443,963,107 and 442,895,261 issued and outstanding at December 31, 2021 and December 31, 2020, respectively",4024561.0,3447698.0
"Treasury stock at cost (1,564,478 shares at December 31, 2021)",-824190.0,0.0
Accumulated other comprehensive income (loss),-40495.0,44398.0
Retained earnings,12689372.0,7573144.0
Total stockholders’ equity,15849248.0,11065240.0
Total liabilities and stockholders’ equity,44584663.0,39280359.0